import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        {
            name: 'Paneer Butter Masala',
            category: 'Veg',
            price: 180,
            description: 'Cottage cheese cubes in a rich buttery tomato sauce.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/paneer-butter-masala-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Veg Biryani',
            category: 'Veg',
            price: 160,
            description: 'Basmati rice cooked with vegetables and aromatic spices.',
            imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/08/vegetable-biryani-1.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Masala Dosa',
            category: 'Veg',
            price: 120,
            description: 'Crispy dosa filled with spicy mashed potatoes.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/masala-dosa-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Chole Bhature',
            category: 'Veg',
            price: 150,
            description: 'Spicy chickpeas served with fried bread.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/chole-bhature-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mushroom Curry',
            category: 'Veg',
            price: 170,
            description: 'Mushrooms cooked in onion-tomato gravy with Indian spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/mushroom-curry.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Palak Paneer',
            category: 'Veg',
            price: 190,
            description: 'Soft paneer cubes in a creamy spinach gravy.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/palak-paneer.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Aloo Paratha',
            category: 'Veg',
            price: 100,
            description: 'Stuffed wheat flatbread with spiced potato filling.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/aloo-paratha.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Veg Fried Rice',
            category: 'Veg',
            price: 130,
            description: 'Fried rice mixed with fresh vegetables and soy sauce.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/veg-fried-rice.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Paneer Tikka',
            category: 'Veg',
            price: 210,
            description: 'Grilled paneer cubes marinated with yogurt and spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/paneer-tikka.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Dal Makhani',
            category: 'Veg',
            price: 160,
            description: 'Creamy black lentil curry slow-cooked with butter and cream.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/dal-makhani-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Biryani',
            category: 'Non-Veg',
            price: 220,
            description: 'Fragrant basmati rice layered with marinated chicken and spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/chicken-biryani-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mutton Curry',
            category: 'Non-Veg',
            price: 280,
            description: 'Tender mutton pieces slow-cooked in spicy curry sauce.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/mutton-curry.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Fish Fry',
            category: 'Non-Veg',
            price: 200,
            description: 'Crispy fried fish marinated in tangy South Indian spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/fish-fry.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Butter Chicken',
            category: 'Non-Veg',
            price: 250,
            description: 'Chicken in creamy buttery tomato gravy.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/butter-chicken-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Prawn Masala',
            category: 'Non-Veg',
            price: 270,
            description: 'Juicy prawns cooked in spicy onion-tomato sauce.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/prawn-masala.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Chicken 65',
            category: 'Non-Veg',
            price: 180,
            description: 'Crispy fried chicken pieces with curry leaves and spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/chicken-65-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Egg Curry',
            category: 'Non-Veg',
            price: 150,
            description: 'Boiled eggs simmered in spicy tomato gravy.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/egg-curry-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Tandoori Chicken',
            category: 'Non-Veg',
            price: 260,
            description: 'Roasted chicken marinated with yogurt and tandoori spices.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/tandoori-chicken-recipe.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Fried Rice',
            category: 'Non-Veg',
            price: 180,
            description: 'Fried rice with tender chicken and vegetables.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/chicken-fried-rice.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mutton Biryani',
            category: 'Non-Veg',
            price: 290,
            description: 'Rich biryani layered with mutton and aromatic basmati rice.',
            imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/mutton-biryani.jpg',
            availability: true,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully - 20 items from Vicky\'s Kitchen added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});